camunda:
  bpm:
    admin-user:
      id: lllimbo
      password: lllimbo
      email: 706725357@qq.com
      first-name: limbo
      last-name: limbo
    database:
      schema-update: true
      jdbc-batch-processing: true

spring:
  datasource:
    url: jdbc:mysql://192.168.2.5:3306/camunda?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xier


